services:
  # PHP/Symfony application
  app:
    build: .
    container_name: munich-backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    depends_on:
      - database
    networks:
      - munich-network

  # Nginx web server
  nginx:
    image: nginx:alpine
    container_name: munich-backend-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - munich-network

  # MySQL database
  database:
    image: mysql:8.0
    container_name: munich-backend-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: munich_backend
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - munich-network

  # Redis for caching (optional)
  redis:
    image: redis:alpine
    container_name: munich-backend-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - munich-network

  # Mailhog for email testing (optional)
  mailhog:
    image: mailhog/mailhog
    container_name: munich-backend-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8026:8025"
    networks:
      - munich-network

volumes:
  db_data:

networks:
  munich-network:
    driver: bridge
